#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 25 21:53:29 2021

@author: ninasele
"""

# Som del av et spørrespill skal du lage en klasse for flervalgspørsmål (hele spillet er muligens
# øving 9 og 10). Et flervalgspørsmål skal ha en spørsmålstekst, ei liste med svaralternativer
# (hvert svaralternativ er en tekststreng), og et tall som sier hvilket av svaralternativene som er
# korrekt. Klassen skal ha en _str_ metode som returnerer en streng som inneholder
# spørsmålsteksten og nummerte svaralternativer på et lett leselig format. Klassen skal ha en
# sjekk_svar metode som tar som parameter et heltall som representerer hvilket svar brukeren
# velger. Sjekk_svar metoden skal sjekke om svaret brukeren har oppgitt er korrekt.

class Sporsmaal:
    def __init__(self, sporsmal, svaralternativ, korrekt_svar):
        self.sporsmaal = sporsmal
        self.svaralternativ = svaralternativ
        self.korrekt_svar = korrekt_svar

    def sjekk_svar(self, svar):
        if int(svar) == self.korrekt_svar:
            return True
        else:
            return False

    def __str__(self):
        string = self.sporsmaal + "\n"
        for nummer, valg in enumerate(self.svaralternativ):
            string += str(nummer) + ": " + str(valg) + "\n"
        return string

def lag_sporsmaal():
    liste = []
    liste.append(Sporsmaal("Hvilken farge har bananer?", ["Rosa", "Blå", "Gul", "Rød"], 2))
    liste.append(Sporsmaal("Hvor mange kort er det i en kortstokk?", ["50", "56", "52"], 2))
    liste.append(Sporsmaal("Når har Karoline bursdag?", ["13.juni", "13.juli", "16.juni"], 0))
    liste.append(Sporsmaal("Hvor gammel er Karoline?", ["23", "24", "26"], 2))
    liste.append(Sporsmaal("Hvor mange søsken har Karoline?", ["Har ingen søsken", "1", "2", "3"], 2))
    return liste


def kjor_sporsmaal():
    sporsmaalliste = lag_sporsmaal()
    poeng = 0
    for sporsmaal in sporsmaalliste:
        print(sporsmaal)
        svar = input("> ")
        if sporsmaal.sjekk_svar(svar):
            poeng += 1
            print("Riktig svar! + 1 poeng \n")
        else:
            print("Feil svar! + 0 poeng \n")
    #print("Du fikk " + str(poeng) + " av " + str(len(sporsmaalliste)) + " poeng!")
    if poeng == 0:
        print("Du fikk " + str(poeng) + " av " + str(len(sporsmaalliste)) + " poeng. Ingen riktige. Bedre lykke neste gang!")
    elif 0 < poeng < 3:
        print("Du fikk " + str(poeng) + " av " + str(len(sporsmaalliste)) + " poeng! Rom for forbedring.")
    elif poeng == 4:
        print("Du fikk " + str(poeng) + " av " + str(len(sporsmaalliste)) + " poeng! Bra jobbet, kun én feil!")
    else:
        print("Du fikk " + str(poeng) + " av " + str(len(sporsmaalliste)) + " poeng! Full pott, gratulerer!")


if __name__ == '__main__':
    kjor_sporsmaal()

